name: "can-i-deploy-consumer"
description: "Checks can-i-deploy for a consumer, including gateway-transformed pairs"
inputs:
  brokerUrl:
    description: "Pact Broker URL"
    required: true
  brokerToken:
    description: "Pact Broker token"
    required: true
  consumerName:
    description: "Name of the consumer"
    required: true
  consumerVersion:
    description: "Version (commit SHA) of the consumer"
    required: true
  toEnvironment:
    description: "Environment you want to deploy to"
    required: true
runs:
  using: "node20"
  main: "index.js"