name: "gateway-ensure-webhooks"
description: "Ensures Pact Broker webhooks exist for all gateway-related participants"
inputs:
  brokerUrl:
    description: "Pact Broker URL"
    required: true
  githubToken:
    description: "GitHub token to allow webhooks"
    required: true
  gatewayName:
    description: "Gateway application name"
    required: true
runs:
  using: "node20"
  main: "index.js"