name: "consumer-record-deployment"
description: "Records deployment for a Consumer and its Consumer-to-gateway participants"

inputs:
  brokerUrl:
    description: "Pact Broker URL"
    required: true

  applicationName:
    description: "Name of the Consumer application"
    required: true

  version:
    description: "Version or commit SHA of the Consumer application"
    required: true

  environment:
    description: "Environment being deployed to"
    required: true

runs:
  using: "node24"
  main: "index.js"