name: "gateway-record-deployment"
description: "Records deployment for all gateway-to-provider participants"

inputs:
  brokerUrl:
    description: "Pact Broker URL"
    required: true

  applicationName:
    description: "Name of the gateway application"
    required: true

  version:
    description: "Version or commit SHA of the gateway application"
    required: true

  environment:
    description: "Environment being deployed to"
    required: true

runs:
  using: "node24"
  main: "index.js"